/* Generated By:JavaCC: Do not edit this line. PajeGrammarConstants.java */
package br.ufrgs.inf.tlbellini;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PajeGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BREAK = 5;
  /** RegularExpression Id. */
  int EVENT_DEF_BEGIN = 6;
  /** RegularExpression Id. */
  int EVENT_DEF = 7;
  /** RegularExpression Id. */
  int EVENT_DEF_END = 8;
  /** RegularExpression Id. */
  int EVENT_DEF_ALIAS = 9;
  /** RegularExpression Id. */
  int EVENT_DEF_TYPE = 10;
  /** RegularExpression Id. */
  int EVENT_DEF_NAME = 11;
  /** RegularExpression Id. */
  int EVENT_DEF_COLOR = 12;
  /** RegularExpression Id. */
  int EVENT_DEF_START_CONTAINER_TYPE = 13;
  /** RegularExpression Id. */
  int EVENT_DEF_END_CONTAINER_TYPE = 14;
  /** RegularExpression Id. */
  int EVENT_DEF_CONTAINER = 15;
  /** RegularExpression Id. */
  int EVENT_DEF_TIME = 16;
  /** RegularExpression Id. */
  int EVENT_DEF_START_CONTAINER = 17;
  /** RegularExpression Id. */
  int EVENT_DEF_END_CONTAINER = 18;
  /** RegularExpression Id. */
  int EVENT_DEF_VALUE = 19;
  /** RegularExpression Id. */
  int EVENT_DEF_KEY = 20;
  /** RegularExpression Id. */
  int EVENT_DEF_LINE = 21;
  /** RegularExpression Id. */
  int EVENT_DEF_FILE = 22;
  /** RegularExpression Id. */
  int EVENT_DEF_FIELD_TYPE_STRING = 23;
  /** RegularExpression Id. */
  int EVENT_DEF_FIELD_TYPE_FLOAT = 24;
  /** RegularExpression Id. */
  int EVENT_DEF_FIELD_TYPE_DOUBLE = 25;
  /** RegularExpression Id. */
  int EVENT_DEF_FIELD_TYPE_INT = 26;
  /** RegularExpression Id. */
  int EVENT_DEF_FIELD_TYPE_HEX = 27;
  /** RegularExpression Id. */
  int EVENT_DEF_FIELD_TYPE_DATE = 28;
  /** RegularExpression Id. */
  int EVENT_DEF_FIELD_TYPE_COLOR = 29;
  /** RegularExpression Id. */
  int PAJE_DEFINE_CONTAINER_TYPE = 30;
  /** RegularExpression Id. */
  int PAJE_DEFINE_VARIABLE_TYPE = 31;
  /** RegularExpression Id. */
  int PAJE_DEFINE_STATE_TYPE = 32;
  /** RegularExpression Id. */
  int PAJE_DEFINE_EVENT_TYPE = 33;
  /** RegularExpression Id. */
  int PAJE_DEFINE_LINK_TYPE = 34;
  /** RegularExpression Id. */
  int PAJE_DEFINE_ENTITY_VALUE = 35;
  /** RegularExpression Id. */
  int PAJE_CREATE_CONTAINER = 36;
  /** RegularExpression Id. */
  int PAJE_DESTROY_CONTAINER = 37;
  /** RegularExpression Id. */
  int PAJE_SET_VARIABLE = 38;
  /** RegularExpression Id. */
  int PAJE_ADD_VARIABLE = 39;
  /** RegularExpression Id. */
  int PAJE_SUB_VARIABLE = 40;
  /** RegularExpression Id. */
  int PAJE_SET_STATE = 41;
  /** RegularExpression Id. */
  int PAJE_PUSH_STATE = 42;
  /** RegularExpression Id. */
  int PAJE_POP_STATE = 43;
  /** RegularExpression Id. */
  int PAJE_RESET_STATE = 44;
  /** RegularExpression Id. */
  int PAJE_START_LINK = 45;
  /** RegularExpression Id. */
  int PAJE_END_LINK = 46;
  /** RegularExpression Id. */
  int PAJE_NEW_EVENT = 47;
  /** RegularExpression Id. */
  int INT = 48;
  /** RegularExpression Id. */
  int FLOAT = 49;
  /** RegularExpression Id. */
  int DIGIT = 50;
  /** RegularExpression Id. */
  int STRING = 51;
  /** RegularExpression Id. */
  int CHAR = 52;
  /** RegularExpression Id. */
  int LETTER = 53;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 4>",
    "<BREAK>",
    "\"%EventDef\"",
    "\"%\"",
    "\"%EndEventDef\"",
    "\"Alias\"",
    "<EVENT_DEF_TYPE>",
    "\"Name\"",
    "\"Color\"",
    "<EVENT_DEF_START_CONTAINER_TYPE>",
    "<EVENT_DEF_END_CONTAINER_TYPE>",
    "\"Container\"",
    "\"Time\"",
    "<EVENT_DEF_START_CONTAINER>",
    "<EVENT_DEF_END_CONTAINER>",
    "\"Value\"",
    "\"Key\"",
    "\"Line\"",
    "\"File\"",
    "\"string\"",
    "\"float\"",
    "\"double\"",
    "\"int\"",
    "\"hex\"",
    "\"date\"",
    "\"color\"",
    "\"PajeDefineContainerType\"",
    "\"PajeDefineVariableType\"",
    "\"PajeDefineStateType\"",
    "\"PajeDefineEventType\"",
    "\"PajeDefineLinkType\"",
    "\"PajeDefineEntityValue\"",
    "\"PajeCreateContainer\"",
    "\"PajeDestroyContainer\"",
    "\"PajeSetVariable\"",
    "\"PajeAddVariable\"",
    "\"PajeSubVariable\"",
    "\"PajeSetState\"",
    "\"PajePushState\"",
    "\"PajePopState\"",
    "\"PajeResetState\"",
    "\"PajeStartLink\"",
    "\"PajeEndLink\"",
    "\"PajeNewEvent\"",
    "<INT>",
    "<FLOAT>",
    "<DIGIT>",
    "<STRING>",
    "<CHAR>",
    "<LETTER>",
  };

}
